name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  test:
    name: Test
    runs-on: macos-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=14.4,name=iPhone 8']
    steps:
      - name: Checkout
        uses: actions/checkout@main
        - name: Build
          run: swift build
        - name: Run tests
          run: swift test
        env:
         destination: ${{ matrix.destination }}
