name: Swift

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          cd Source/XCode/Apps/CookingApp
          swift build
      - name: Run tests
        run: |
          cd Source/XCode/Apps/CookingApp
          swift test
